name: task_master
description: A Flutter package to help you implement a feature-rich task management system into your application
version: 0.0.1
homepage: https://github.com/Knightro63/task_master

environment:
  sdk: '>=2.18.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  flutter_colorpicker: ^1.0.3
  english_words: ^4.0.0
  list_english_words: ^0.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
